name: ZillowBnb
channels:
  - defaults
dependencies:
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py37_0
  - openssl=1.1.1b
  - pip=19.1.1=py37_0
  - python=3.7.3
  - setuptools=41.0.1=py37_0
  - sqlite=3.28.0
  - wheel=0.33.4=py37_0
